version: '3.8'
services:
  etcd1:
    image: quay.io/coreos/etcd:v3.5.11
    container_name: etcd1
    ports:
      - "2379:2379"
      - "2380:2380"
    environment:
      - ETCD_NAME=etcd1
      - ETCD_LISTEN_CLIENT_URLS=[http://0.0.0.0:2379](http://0.0.0.0:2379)
      - ETCD_ADVERTISE_CLIENT_URLS=[http://127.0.0.1:2379](http://127.0.0.1:2379)
      - ETCD_LISTEN_PEER_URLS=[http://0.0.0.0:2380](http://0.0.0.0:2380)
      - ETCD_ADVERTISE_PEER_URLS=[http://127.0.0.1:2380](http://127.0.0.1:2380)
      - ETCD_INITIAL_CLUSTER=etcd1=[http://127.0.0.1:2380](http://127.0.0.1:2380),etcd2=[http://127.0.0.1:2381](http://127.0.0.1:2381),etcd3=[http://127.0.0.1:2382](http://127.0.0.1:2382)
      - ETCD_INITIAL_CLUSTER_STATE=new
    volumes:
      - etcd-data-1:/data
    networks:
      etcd-net:
        ipv4_address: 172.20.0.10

  etcd2:
    image: quay.io/coreos/etcd:v3.5.11
    container_name: etcd2
    ports:
      - "2389:2379"
      - "2390:2380"
    environment:
      - ETCD_NAME=etcd2
      - ETCD_LISTEN_CLIENT_URLS=[http://0.0.0.0:2379](http://0.0.0.0:2379)
      - ETCD_ADVERTISE_CLIENT_URLS=[http://127.0.0.1:2389](http://127.0.0.1:2389)
      - ETCD_LISTEN_PEER_URLS=[http://0.0.0.0:2380](http://0.0.0.0:2380)
      - ETCD_ADVERTISE_PEER_URLS=[http://127.0.0.1:2381](http://127.0.0.1:2381)
      - ETCD_INITIAL_CLUSTER=etcd1=[http://127.0.0.1:2380](http://127.0.0.1:2380),etcd2=[http://127.0.0.1:2381](http://127.0.0.1:2381),etcd3=[http://127.0.0.1:2382](http://127.0.0.1:2382)
      - ETCD_INITIAL_CLUSTER_STATE=new
    volumes:
      - etcd-data-2:/data
    networks:
      etcd-net:
        ipv4_address: 172.20.0.11
    depends_on:
      - etcd1

  etcd3:
    image: quay.io/coreos/etcd:v3.5.11
    container_name: etcd3
    ports:
      - "2409:2379"
      - "2410:2380"
    environment:
      - ETCD_NAME=etcd3
      - ETCD_LISTEN_CLIENT_URLS=[http://0.0.0.0:2379](http://0.0.0.0:2379)
      - ETCD_ADVERTISE_CLIENT_URLS=[http://127.0.0.1:2409](http://127.0.0.1:2409)
      - ETCD_LISTEN_PEER_URLS=[http://0.0.0.0:2380](http://0.0.0.0:2380)
      - ETCD_ADVERTISE_PEER_URLS=[http://127.0.0.1:2382](http://127.0.0.1:2382)
      - ETCD_INITIAL_CLUSTER=etcd1=[http://127.0.0.1:2380](http://127.0.0.1:2380),etcd2=[http://127.0.0.1:2381](http://127.0.0.1:2381),etcd3=[http://127.0.0.1:2382](http://127.0.0.1:2382)
      - ETCD_INITIAL_CLUSTER_STATE=new
    volumes:
      - etcd-data-3:/data
    networks:
      etcd-net:
        ipv4_address: 172.20.0.12
    depends_on:
      - etcd2

volumes:
  etcd-data-1:
  etcd-data-2:
  etcd-data-3:

networks:
  etcd-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
